//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Youtube.Types
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Comment
	{
		public virtual int CommentID
		{
			get;
			private set;
		}

		public virtual DateTime UploadDate
		{
			get;
			private set;
		}

		public virtual string Content
		{
			get;
			private set;
		}

		public virtual int UpVotes
		{
			get;
			private set;
		}

		public virtual int DownVotes
		{
			get;
			private set;
		}

		public virtual bool IsReply
		{
			get;
			private set;
		}

		public virtual IEnumerable<Comment> Replies
		{
			get;
			set;
		}

		public virtual Channel Author
		{
			get;
			set;
		}

		public virtual void RemoveUpVote()
		{
			throw new System.NotImplementedException();
		}

		public virtual void RemoveDownVote()
		{
			throw new System.NotImplementedException();
		}

		public virtual void EditContent(string content)
		{
			throw new System.NotImplementedException();
		}

		public virtual void AddUpVote()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AddDownVote()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AddReply(Comment reply)
		{
			throw new System.NotImplementedException();
		}

	}
}

