//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Youtube.Types
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Livestream
	{
		public virtual IEnumerable<ChatMessage> Messages
		{
			get;
			set;
		}

		public virtual Channel Streamer
		{
			get;
			set;
		}

		public virtual void AddMessage(ChatMessage message)
		{
			throw new System.NotImplementedException();
		}

	}
}

