//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Youtube.Types
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Playlist
	{
		public virtual int PlaylistID
		{
			get;
			private set;
		}

		public virtual string Title
		{
			get;
			private set;
		}

		public virtual string Description
		{
			get;
			private set;
		}

		public virtual DateTime UploadDate
		{
			get;
			private set;
		}

		public virtual IEnumerable<Video> Videos
		{
			get;
			set;
		}

		public virtual Channel Creator
		{
			get;
			set;
		}

		public virtual void AddVideo(Video video)
		{
			throw new System.NotImplementedException();
		}

		public virtual void RemoveVideo(Video video)
		{
			throw new System.NotImplementedException();
		}

		public virtual void MoveDown(Video video)
		{
			throw new System.NotImplementedException();
		}

		public virtual void MoveDown(int index)
		{
			throw new System.NotImplementedException();
		}

		public virtual void MoveUP(Video video)
		{
			throw new System.NotImplementedException();
		}

		public virtual void MoveUp(int index)
		{
			throw new System.NotImplementedException();
		}

		public virtual void EditDescription(string description)
		{
			throw new System.NotImplementedException();
		}

		public virtual void EditTitle(string title)
		{
			throw new System.NotImplementedException();
		}

	}
}

