//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Youtube.Types
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User
	{
		public virtual string Email
		{
			get;
			set;
		}

		public virtual IEnumerable<Channel> Channels
		{
			get;
			set;
		}

		public virtual void AddChannel(Channel channel)
		{
			throw new System.NotImplementedException();
		}

	}
}

